version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8-buster-node-browsers
      - image: circleci/redis:latest
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: test
    environment:
      PYTHONPATH: ~/repo
      ELECTRON_DRIVER: electron-driver
      ELECTRON_CHROME_VERSION: 91.0.4472.101
      POSTGRES_DSN: host=localhost port=5432 dbname=circle_test user=root password=test

    working_directory: ~/repo
    parallelism: 8

    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Install
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt --quiet
            pip install -r requirements-dev.txt --quiet
            npm ci

      - run:
          name: Install chromedriver version for electron.
          command: |
            mkdir ~/electron-driver
            curl https://chromedriver.storage.googleapis.com/$ELECTRON_CHROME_VERSION/chromedriver_linux64.zip -o ~/electron-driver/driver.zip
            unzip ~/electron-driver/driver.zip -d ~/electron-driver
            mv ~/electron-driver/chromedriver ~/electron-driver/electron-driver

      - save_cache:
          paths:
            - ./venv
            - ./node_modules/
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Build
          command: |
            . venv/bin/activate
            pip install -e .
            npm run build
            npm run build:dazzler

      - run:
          name: Test
          command: |
            . venv/bin/activate
            echo 'export PATH=$HOME/electron-driver:$PATH' >> $BASH_ENV
            source $BASH_ENV
            TEST_FILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)
            mkdir -p test-results
            pytest -ra --junitxml=~/test-reports/results.xml --cov=dazzler $TEST_FILES

      - store_artifacts:
          path: ~/test-reports
          destination: test-reports

      - store_test_results:
          path: ~/test-reports
