export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const WINDOW_MOVE = 'WINDOW_MOVE';
export const WINDOW_FULLSCREEN = 'WINDOW_FULLSCREEN';
export const WINDOW_STATE_INIT = 'WINDOW_STATE_INIT';
export const WINDOW_SET_BOUNDS = 'WINDOW_SET_BOUNDS';
export const WINDOW_SET_FULLSCREEN = 'WINDOW_SET_FULLSCREEN';
export const WINDOW_SET_RESIZABLE = 'WINDOW_SET_RESIZABLE';
export const WINDOW_SET_MINIMIZABLE = 'WINDOW_SET_MINIMIZABLE';
export const WINDOW_SET_MAXIMIZABLE = 'WINDOW_SET_MAXIMIZABLE';
export const WINDOW_SET_CLOSABLE = 'WINDOW_SET_CLOSABLE';
export const WINDOW_SET_MOVABLE = 'WINDOW_SET_MOVABLE';

export const WINDOW_FOCUS = 'WINDOW_FOCUS';
export const WINDOW_SET_FOCUS = 'WINDOW_SET_FOCUS';

export const WINDOW_MINIMIZE = 'WINDOW_MINIMIZE';
export const WINDOW_SET_MINIMIZED = 'WINDOW_SET_MINIMIZED';

export const WINDOW_MAXIMIZE = 'WINDOW_MAXIMIZE';
export const WINDOW_SET_MAXIMIZED = 'WINDOW_SET_MAXIMIZED';
export const WINDOW_CLOSE = 'WINDOW_CLOSE';
